/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class StreamScanner {
  constructor(configJson: string)
  push(chunk: string): string
  finish(): string
}
export type JsStreamScanner = StreamScanner

export declare function extractPackages(text: string, ecosystems: Array<string>): string

export declare function redact(text: string, entities: Array<string>, mode: string): string

export declare function restore(text: string, vaultJson: string): string

export declare function scanInjection(text: string, sensitivity: string): string

export declare function scanSecretLeak(text: string): string

export declare function scanSecrets(text: string): string

export declare function scanUrls(text: string): string
